### ISSUE TITLE
Spigot / Bukkit ? 

### ISSUE THREAD

**Issue by Amauryroco** [AmauryCarrade/UHPlugin#104]
Hello !

First, I need to tell you that I don't know the difference between Spigot and Bukkit...
Apparently this plugin is compatible with Spigot, but are WorldBorder, dynmpa, etc compatible too ?
Is is better to have a bukkit server or a spigot server for this plugin ? What's the difference ?

**Comment by AmauryCarrade** [comment]
Bukkit is an API, a base, a blueprint for Minecraft plugins if you want. You, as an end user, never use it directly.

CraftBukkit is a server, compatible with all plugins that follows Bukkit's guidelines. Spigot is another one, with a little few things added, and a great global optimization.

So: **if a plugin is compatible with CraftBukkit** (we call these plugins: “Bukkit plugins”), **it will always be compatible with Spigot** (if the version is the same, of course). On the other side, a Spigot plugin will in most cases be compatible with CraftBukkit (a very few exceptions remain).

The performances of the Spigot server are way better than the ones of the CraftBukkit one. So, **I recommend you to use Spigot**.
