### ISSUE TITLE
Execute Delays

### ISSUE THREAD

**Issue by jdtzmn** [AmauryCarrade/UHPlugin#113]
I am trying to make the ultra hardcore server automatically restart itself. The "exec: restart" command is working fine, but before it I tried to put a one minute delay and it won't work. Here is a snippet of my code:
```
execute-end:
   - delay: "01:00"
   - exec: restart
```

I also tried using:
```
execute-end:
   - delay: "01"
   - exec: restart
```

**Comment by AmauryCarrade** [comment]
Use this instead:
```
execute-end:
   - delay: "01"
     exec: restart
```
(notice the dash).

There is one dash per command/command options.
