### ISSUE TITLE
Auto-Generate new terrain

### ISSUE THREAD

**Issue by jdtzmn** [AmauryCarrade/UHPlugin#114]
I would like to make this plugin the main thing on my server, so I would like to be able to specify a world in the config, and at the end of the game, it will automatically reset the arena and create new terrain. Right now I am running commands at the end which, (using multiverse-core), recreate the world and implement a worldborder using /worldborder, but I have to temporarily shut down the server...

**Comment by AmauryCarrade** [comment]
You cannot do that with this plugin, and it's not his objective. Other plugins probably exists to do that (using a rolling world, maybe).
