### ISSUE TITLE
Worldborder size announcement wrong after /uh border set command is run.

### ISSUE THREAD

**Issue by JBTollak** [AmauryCarrade/UHPlugin#116]
When setting a new size of worldborder eg: /uh border set 400
the announcement given in chat reads: "Worldborder is now 400×400". In fact the measurements is 200×200. Because the size given in set border command displays diameter.
I hope it makes sense.

I am using:
version: 1.3 dev.
build number: 7380b61b9e

**Comment by AmauryCarrade** [comment]
Yes, but 400 *is* the diameter of the map—or I'm wrong?

The map is open from -200 to 200 (with a 0;0-center), so it's 400 blocks per 400 blocks in surface.

**Comment by JBTollak** [comment]
I will try to explain again :-)
I set the diameter to 400 with /uh border set 400.
The announcement then says: "border is now 400*400". ( which would give a diameter of 800).

What it should announce is 200*200.

**Comment by JBTollak** [comment]
Hi.
I talked this through with a friend of mine, and I must admit I was wrong.

You are right about that 400 IS the diameter.
Sorry for troubling you :)

**Comment by AmauryCarrade** [comment]
No problem :) .
