### ISSUE TITLE
Add an option to ignore teams while generating spawnpoints / teleporting players

### ISSUE THREAD

**Issue by prokopyl** [AmauryCarrade/UHPlugin#62]
A bit like the /spreadplayers command with the respectTeams argument set to false.

This would make a kind of game where all players start alone, and would have to do the basic survival stuff before exploring to find their teammates, and hope not to meet any ennemies on the way.

Used in conjunction with the MumbleLink mod, this would allow to have huge teams (like 10+ players) without having to handle a whole mess, but still having the fun of playing with more people. :)

(And yes, the idea is from the Mindcrack UHC S19.)

**Comment by AmauryCarrade** [comment]
Implemented with tags.

```
/uh start ignoreTeams:true
/uh start ignoreTeams:true slow:true
```
