### ISSUE TITLE
/uh resurrect <player> don't runs in #151

### ISSUE THREAD

**Issue by YoLaw** [AmauryCarrade/UHPlugin#72]
Hello,
/uh resurrect <player> don't runs in #151 :/

**Comment by AmauryCarrade** [comment]
I cannot work on this project this week, but I'll check that as soon as possible (next sunday).

**Comment by AmauryCarrade** [comment]
Can you precise what you mean by « it don't runs »? Maybe with errors in the console, or simply the behavior observed?

**Comment by YoLaw** [comment]
If i type the command, for exemple "/uh resurrect YoLaw", I have a message: "this plyer is not in game or is in life"... But the player is dead :/

**Comment by AmauryCarrade** [comment]
Ok, thanks. I'll check that (sunday, reason explained before).

**Comment by AmauryCarrade** [comment]
I tested that – I wasn't able to reproduce.

**Comment by AmauryCarrade** [comment]
Can you give exact and complete steps to reproduce? I mean, what happened to the player to be resurrected.

**Comment by YoLaw** [comment]
Finaly, it runs... Maybe it was a bug from my server... Sorry... :/

**Comment by AmauryCarrade** [comment]
No problem, thanks for your answer!
