### ISSUE TITLE
the 1.8 worldborder

### ISSUE THREAD

**Issue by yannickgrammont** [AmauryCarrade/UHPlugin#73]
- Add the vanilla worldborder and perhaps an automatic resize (like on epicube server UHC the worldborder start reducing slowly after XX episode).
- Add the worldborder info in the sidebar (time before starting reduce and while reducing the size of the map)

**Comment by AmauryCarrade** [comment]
Partial duplicate. I'll close this issue and add the not duplicated ideas to #26.
