### ISSUE TITLE
§ Causes an A in the message

### ISSUE THREAD

**Issue by DanSpedey** [AmauryCarrade/UHPlugin#79]
Read the title :)

**Comment by AmauryCarrade** [comment]
Where? Context? Version? Steps to reproduce? Cf. the [guidelines for contributing](https://github.com/AmauryCarrade/UHPlugin/blob/master/CONTRIBUTING.md).

(Workaround: use `&` instead of `§`.)

**Comment by DanSpedey** [comment]
Ultra Hardcore plugin - version 1.1.3 dev  
Build number: 08b1a362f4

Using it on the scoreboard, & causes the plugin to make the title Attack the Patrick or something like that

**Comment by AmauryCarrade** [comment]
Can you write here this part of your config file? To see exactly what is happening.

```yaml
scoreboard:
    title: <your title>
```
(Lines 54-55.)

**Comment by DanSpedey** [comment]
scoreboard:
    title: &6&lMineHub UHC

**Comment by AmauryCarrade** [comment]
Use quotes around the title, or `§`, or both. I tested both of these cases with your title, without problems.

`&6&lMineHub` have a special signification in YAML, the YAML parser tries to interpret it (and it fails); that's why the plugin falls back to the default value in the configuration.

**Comment by AmauryCarrade** [comment]
(Where is your A?)

**Comment by DanSpedey** [comment]
It works now, thanks

**Comment by AmauryCarrade** [comment]
You're welcome :) .
