### ISSUE TITLE
Sending JSON messages to the player without ProtocolLib

### ISSUE THREAD

**Issue by prokopyl** [AmauryCarrade/UHPlugin#81]
This can be acheived by using the vanilla command /tellraw, hence reducing the dependency to ProtocolLib : 

```java
Bukkit.getServer().dispatchCommand(Bukkit.getConsoleSender(), 
    "tellraw " + player.getName() + " " + rawMessage);
```

**Comment by AmauryCarrade** [comment]
Hmm, you're right, I'll add this as an alternative (but I keep using ProtocolLib if available to avoid console spam).

**Comment by prokopyl** [comment]
Unless there was a recent change I am not aware of, calling dispatchCommand does not print anything to the server console. :)

**Comment by AmauryCarrade** [comment]
My bad, you're right, I confused with the broadcasts on the administrative channel of some commands (/title, etc.).

 --
 Amaury Carrade
 amaury@carrade.eu
 Clef GnuPG : 0x640581B6
 4 février 2015 17:42 "ProkopyL"  a écrit:  

	  
	Unless there was a recent change I am not aware of, calling dispatchCommand does not print anything to the server console. :)
