### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by Amauryroco** [AmauryCarrade/UHPlugin#82]
Hello !

I am aware of the work and effort you put into this plugin, and I really do love it, but when will the next build be available ? Or is the 1.1.3 Snapshot constantly updated ?

And could you add something so that we can make the spawn rate of Spiders bigger ? I find it really hard to get a bow in an Uhc, and changing the spawn rate (that can be changed in the config file) would really make Uhc less dependent on luck.

Thank you =D

Edited: I have also another question: When a players gets killed, I can't edit the config file so that the name of the player is colored in his team color in the tchat...

**Comment by Amunak** [comment]
I'm not the author but I can at least aswer this: 1.1.3 is getting continuously updated, just use builds from the [jenkins CI server](http://jenkins.carrade.eu/job/UltraHardcoreReloaded/). A build is created for each commit, it's great! (though it could be buggy and unstable)

**Comment by Amauryroco** [comment]
@Amunak Thanks a lot ! I just hope it wont be full of bugs =D

**Comment by Amauryroco** [comment]
Is that the one I need to download ? http://prntscr.com/61e3m2

**Comment by jonyroda97** [comment]
Yes it is

The 1.2 release it's about to appear. See the milestones (https://github.com/AmauryCarrade/UHPlugin/milestones)

**Comment by Amauryroco** [comment]
Thanks ! 
@jonyroda97 @AmauryCarrade I really appreciate the work and effort you put in this plugin =D

**Comment by jonyroda97** [comment]
Thank YOU! 
If anyone used the plugin all this was kinda for nothing :smiley:

**Comment by AmauryCarrade** [comment]
Just to answer to this:

> And could you add something so that we can make the spawn rate of Spiders bigger ? I find it really hard to get a bow in an UHC, and changing the spawn rate (that can be changed in the config file) would really make UHC less dependent on luck.

No. Let's me explain why.
This plugin is an UHC plugin. Not a plugin to change the spawn rates, or to add kits, or to add kill rewards¹, or, or, or. Plugins already exists for these tasks, and you should use them.
As example for your use, you could use [this](http://dev.bukkit.org/bukkit-plugins/mobspawnsettings/) (not tested by me). You can also increase the mob spawn rate in the `bukkit.yml` file.


> Thanks a lot ! I just hope it wont be full of bugs =D

We comes to the end of this update, the stable 1.2 version will be published soon (next week probably, I still have some tests to do in multiplayer).
So, yes, the current builds are pretty stable (I just found a possible bug on the spawn point generator, I'll check that soon).

**Comment by jonyroda97** [comment]
@AmauryCarrade with that can you send a link to a plugin that gives kill rewards and works with 1.8 and other (if not the same) that works with 1.7.10?

**Comment by Amauryroco** [comment]
@jonyroda97 I have one I use. It's called DeathTreasure :)
Hopefully it will help you.

**Comment by Amauryroco** [comment]
@AmauryCarrade I understand what you mean.
Although, if I must say, you seemed pretty unhappy about what I said earlier.

**Comment by jonyroda97** [comment]
@Amauryroco I was looking more to a plugin that drops the items (like the head when it's killed)...

**Comment by Amauryroco** [comment]
@jonyroda97 Sorry, I've searched days for a plugin like that but only found DeathTreasure... :/

**Comment by jonyroda97** [comment]
I was looking now for one but only appears with economy rewards.
I think that @AmauryCarrade should rethink about that...

**Comment by Amauryroco** [comment]
@jonyroda97 Apparently he doesn't want to.

**Comment by AmauryCarrade** [comment]
> I was looking now for one but only appears with economy rewards.
> I think that @AmauryCarrade should rethink about that...

Just to be clear, I said I doesn't want to include such a feature *into the UHCr plugin*. I can make another plugin for that (it's not very complicated – I already developed a plugin [with a similar feature](https://github.com/AmauryCarrade/LightHeads/). I'll think about this.

**Comment by jonyroda97** [comment]
@AmauryCarrade that would be awesome! :sweat_smile:

**Comment by AmauryCarrade** [comment]
> Edited: I have also another question: When a players gets killed, I can't edit the config file so that the name of the player is colored in his team color in the tchat...

You can with the latest builds. (Edit just seen.)  
 

> Although, if I must say, you seemed pretty unhappy about what I said earlier.

I'm not. But I want to keep this plugin centered on his goal :) .
@Amunak explained the situation pretty well:
> Oh and I'm sure you could find some other plugins focused just on mob spawning, I don't think something like that really belongs to this plugin as it is.  

-----
(@Amauryroco)

**Comment by Amauryroco** [comment]
@AmauryCarrade Okay thank you ! :D
