### ISSUE TITLE
1.2 Stable Uh Reloaded: 1.8 or 1.7 ?

### ISSUE THREAD

**Issue by Amauryroco** [AmauryCarrade/UHPlugin#84]
Quick question !

Will the 1.2 stable version of the Ultra Hardcore Reloaded plugin work on 1.8 or only on 1.7 ?

**Comment by AmauryCarrade** [comment]
Both.
It will be the last release supporting the 1.7.9 version of CraftBukkit, by the way.

**Comment by Amauryroco** [comment]
Okay, you ! ^^
