### ISSUE TITLE
UH border warning timer glitches the on-screen scoreboard

### ISSUE THREAD

**Issue by Amunak** [AmauryCarrade/UHPlugin#86]
The timer of `/uh border warning` does not disappear when it finishes. That is probably the intended behavior. However when you then use the command again, the text saying what the timer is shifts one entry up removing that entry (the actual time stays where it's supposed to be).

This is what it looks like after applying that command a few times:
![fucked up timer](http://puu.sh/fSh8z/6c696a18e1.jpg)
(the scoreboard gets erasedby the timer text)

The only known way to fix this is by reloading or restarting the server as you can't even use the timer commands to remove that timer.

This happens on rev 2328a798d93bca3c829a1ce47ae1b10482d068b8 (build 169).

**Comment by AmauryCarrade** [comment]
Not supposed to happens. I was aware of some of these instabilities, but they are very hard to obtain unlike this one. I'll check that.

**Comment by AmauryCarrade** [comment]
Cannot reproduce with the default config. Can you give me your `config.yml` (the `scoreboard` and `episodes` parts)? Thanks.
