### ISSUE TITLE
1.8 Border ? & Other questions

### ISSUE THREAD

**Issue by Amauryroco** [AmauryCarrade/UHPlugin#97]
Hello !

I wanted to ask if the 1.8 borders were added to the plugin so that it is managed by it. It would be so much easier than the Bedrock walls.

Can you put the config file to download or just post and image on the main page so that people don't have to install everything but could just edit the file in advance ? :underage: 

If I am a spectator before the game starts, I am not counted as a player. But if I change it after so that I am in Gamemode 3 (it's easier to spectate with it), will it count me as a player ? And can you put something so that when players are in Gamemode 3 they are not counted as players in the game ?

Thank you !

**Comment by jonyroda97** [comment]
1.8 Borders it's a feature already to be implemented
Issue: #26

**Comment by Amauryroco** [comment]
@jonyroda97 Oh okay thank you, I didn't know that ^^ So it's managed by the plugin ? /uh generatewalls makes 1.8 borders ?

**Comment by jonyroda97** [comment]
@Amauryroco It's not yet implemented but you can use it with the vanilla command.

**Comment by Amauryroco** [comment]
@jonyroda97 Okay thank you ! <3

**Comment by jonyroda97** [comment]
Wait for @AmauryCarrade answer to the other questions :smiley:

**Comment by Amauryroco** [comment]
@jonyroda97 =D

**Comment by AmauryCarrade** [comment]
> If I am a spectator before the game starts, I am not counted as a player. But if I change it after so that I am in Gamemode 3 (it's easier to spectate with it), will it count me as a player ?

If you mark a player as a startup spectator, it will remain a non-player until someone executes `/uh resurrect <name>`. You can change your gamemode or anything else without any problem.

> Can you put the config file to download or just post and image on the main page so that people don't have to install everything but could just edit the file in advance ? :underage: 

I don't understand what you want. The future config file when this will be implemented? I don't know, I write the config file when I implement a configurable feature.

**Comment by Amauryroco** [comment]
@AmauryCarrade There is a config.yml (or something like that) that I need to edit so that I customize the plugin before starting the server. Could you put it to download so that I can edit the file on my desktop (computer desktop, not real one) so that I don't have to install the plugin before configuring, it saves time.

**Comment by AmauryCarrade** [comment]
Oh, I understand. This file is already available in the repository, [here](https://github.com/AmauryCarrade/UHPlugin/blob/dev/src/main/resources/config.yml). And a link is already in the README, displayed in the homepage of this repository.

**Comment by Amauryroco** [comment]
Ok thank you @AmauryCarrade ^^
